name: unofficial-webapp-todo
version: "0.4"
summary: Unofficial To Do
description: Unofficial wrapper for Microsoft To Do web app.

confinement: strict
base: core18

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  unofficial-webapp-todo-qml:
    after: [desktop-qt5]
    source: .
    plugin: dump
    stage-packages:
      - qmlscene
      - qml-module-qtquick2
      - qml-module-qtquick-window2
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
    organize:
      unofficial-webapp-todo.launcher: bin/unofficial-webapp-todo.launcher

apps:
  word:
    command: unofficial-webapp-todo.launcher "https://to-do.live.com/tasks/" "To Do"
    desktop: snap/gui/todo.desktop
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      DISABLE_WAYLAND: 1
